### ISSUE TITLE
Краш при ломании Краснокаменного мозга

### ISSUE THREAD

**Issue by GedeonGrays** [Ilya3point999K/ThaumicConcilium#1]
Краш репорт: [crash-2024-07-04_20.52.36-server.txt](https://github.com/user-attachments/files/16102053/crash-2024-07-04_20.52.36-server.txt)

Как повторить: 
1. Заспавнить мозг яйцом призыва
2. Сломать мозг в ВЫЖИВАНИИ
3. Наслаждаться крашем

P.S. Дайте знать, если хотите, чтобы я создавал следующие репорты на английском языке.

**Comment by Ilya3point999K** [comment]
Спасибо, исправил, репортить можешь как тебе удобно.
