### ISSUE TITLE
Please add config options for Flux Rifts

### ISSUE THREAD

**Issue by Shahelion** [Ilya3point999K/ThaumicConcilium#11]
Such as the chance for them to spawn when breaking a node (with 0 being an option), and whether or not they can break blocks.

Would it be possible to prevent rifts from appearing until certain milestones were reached? (Such as certain researches)

Also, how do you get rid of these things?

**Comment by Ilya3point999K** [comment]
I can't disable rifts, as they are crucial for player progress. I wanted to add option for block breaking, but forgor ;( Will be in 1.0.5 patch.
Scan a rift for a research hint, it will unlock a branch of rift related researches, first of them will be a way of safe closure of rifts. You'll also need to research focal manipulator and vis conductor focus (it is tradeable from thaumaturges only for completed research) for this.

**Comment by Shahelion** [comment]
What if rifts were created a different way? Until now, breaking nodes in TC4 has always neem a safe way to get essences.

Maybe it only happens with hungry or tainted nodes?

**Comment by Ilya3point999K** [comment]
Addon has a new and more reliable way of obtaining essences. It is the same thing that closes rifts.
Restricting rifts to certain node types will just make this part of the addon harder to discover for a blind player.

**Comment by Shahelion** [comment]
Wait, what closes rifts? I was looking through the mod and didn't see anything that said it did that, but maybe I just missed it.

**Comment by Ilya3point999K** [comment]
![image](https://github.com/user-attachments/assets/a3e2c089-30de-44f3-9bba-c321ebb454a2)
![image](https://github.com/user-attachments/assets/344adfec-ab0e-479c-84ed-ad01feaa5f53)
![image](https://github.com/user-attachments/assets/d06fe955-e50b-48a6-9833-1db6de07ef60)
![image](https://github.com/user-attachments/assets/c85eb39e-aadb-4d3a-9394-cc2c6a35c2e2)

**Comment by Shahelion** [comment]
This is excellent, thank you.

**Comment by Shahelion** [comment]
An idea for rifts: Maybe prevent them from destroying items in the first few seconds? Give the player a chance to realize what's appeared, and grab any essences that dropped, before it starts to be dangerous.
