### ISSUE TITLE
Research entries could be a bit clearer

### ISSUE THREAD

**Issue by Shahelion** [Ilya3point999K/ThaumicConcilium#12]
A number of the Thaumonomicon pages are too vague to really understand how the item or mechanic in question actually functions. Vanilla TC4 pages generally have fairly clear instructions for use, without mentioning actual buttons and keys if possible.

For example, I don't really have a clue how the Vis Conductor focus is supposed to work. I get the vague idea that it can channel vis from one thing into something else, but beyond that, no idea.

Another example, the Valet golem core. It says to give it commands on slips of paper, but I have no idea what a valid command would be. Also, do I just rename a piece of paper in an anvil, or something else?

**Comment by Ilya3point999K** [comment]
I've tried my almost best to explain mechanics while intentionally being vague, arcane magic mysteries and all that. Maybe the problem also is that description is separated between different research.
Without upgrades - vis conductor is only usable to craft specific items on infusion matrix. Vis conductor research only describes the general idea of polished infusions, the process itself is described in the other half - destabilized crystal clusters research
![image](https://github.com/user-attachments/assets/5b4ddf13-e001-4dfa-8920-90226a214f92)
Think of it as an extra jar, you have to lock on it with your focus while infusion process is going on, and when infusion is over - collected vis will be transfered automatically.

Yeah, you have to rename papers on anvil. Golem will react to you saying this phrases in chat, and will go and activate marked block. You probably also want to insert an order upgrade, so you can specifically mark exact phrases to exact places.

**Comment by Shahelion** [comment]
Ohhh, so the papers are just to set keywords to trigger the golem? That's actually really cool.
