### ISSUE TITLE
Crystal Cluster / Conductor Focus

### ISSUE THREAD

**Issue by Shahelion** [Ilya3point999K/ThaumicConcilium#13]
Maybe I'm just not using it right, but I can't figure out how to use the focus on it without it just blowing up.

I also cannot for the life of me figure out the Conductor focus. Most of the time it just does nothing (although I do love the Wisp Cannon).

**Comment by Ilya3point999K** [comment]
It really does nothing, it's only usage (outside of wisp cannon) is channeling vis from clusters. If you have dematerialization upgrade - then you can take vis from cluster, look at some entity, and release focus. Vis for infusion transfers automatically - you just have to collect and hold it till the end of infusion. Halting conduction without either of this 2 vis destinations leads to explosion of cluster.

**Comment by Shahelion** [comment]
Would it be possible to make the explosion not damage blocks, and drop any crystalline essentia from within the crystal?

**Comment by Ilya3point999K** [comment]
I think I could add mobGriefing check. Crystalline essentia won't be dropped, this is a high voltage operation and all that.
