### ISSUE TITLE
Golem Core: Valet

### ISSUE THREAD

**Issue by Shahelion** [Ilya3point999K/ThaumicConcilium#14]
1: Once the core is attached to the golem, I can't mark locations. Right-clicking, even with the bell in hand, opens the golem UI.

2: There is no way to differentiate the commands given. I put two command papers in, but how to tell which is for which mark?

**Comment by Ilya3point999K** [comment]
1) Eh? No problem on my side, golem perfectly available for marking with core attached. Try to update your Gadomancy version just in case you are using not the last.
2) There are, apply order upgrade, that's a vanilla feature.

**Comment by Shahelion** [comment]
I have 1.0.7.3, the latest Gadomancy version.

I did forget about the order upgrade.

**Comment by Shahelion** [comment]
I tested with a few different golem types, but no matter what, it always opens the UI, even with the bell in hand, when the core is attached. 
![2024-07-21_20 48 28](https://github.com/user-attachments/assets/77d81cfa-54f0-4272-8675-08428db0a4d7)

**Comment by Shahelion** [comment]
I also had an idea, if it's possible: Entropy Upgrade allows the commands to be within larger messages. For example, "lamp" is the command. With Entropy, "lamp, please" would also do it. Add some fuzziness on what it looks for.

**Comment by Ilya3point999K** [comment]
The issue with bell is Gadomancy issue, as the same happens with it's cores as well. What exactly causes this, I didn't find out.
