### ISSUE TITLE
"Tainted Magic" entry missing icon

### ISSUE THREAD

**Issue by Shahelion** [Ilya3point999K/ThaumicConcilium#15]
![2024-07-16_20 24 17](https://github.com/user-attachments/assets/719554a9-f2fa-409d-ab91-b01ed669a5b9)

**Comment by Ilya3point999K** [comment]
What version of Tainted Magicyou installed?

**Comment by Shahelion** [comment]
v7.82

I just checked, didn't realize there had been updates since I last downloaded it, although the complete lack of changelogs is annoying.

**Comment by Shahelion** [comment]
Ok yes, works with latest version. I think the texture didn't exist yet in 7.8.2.
