### ISSUE TITLE
Flux Rift size should scale (a bit) with node aspect count

### ISSUE THREAD

**Issue by Shahelion** [Ilya3point999K/ThaumicConcilium#17]
For example, if I have drained a node completely so that it has zero points of anything left, or even just one or two points, it shouldn't make a rift when broken. 

Conversely, if I have built or found a node with thousands or tens of thousands of aspect points (it's happened), it should make a much bigger rift, although there should be an upper cap, of course, to prevent world-eating disasters.

Perhaps a config option for this behaviour vs just the same size every time.

**Comment by Ilya3point999K** [comment]
Rifts for nos scale from node breaker's warp. Guess I'll rework that.

**Comment by Shahelion** [comment]
Ah, that explains why they were all maximum size in my testing world, lol.
