### ISSUE TITLE
Краш с Воином Параноиком

### ISSUE THREAD

**Issue by GedeonGrays** [Ilya3point999K/ThaumicConcilium#2]
Привет о/

Краш репорт: [crash-2024-07-04_21.17.44-server.txt](https://github.com/user-attachments/files/16110086/crash-2024-07-04_21.17.44-server.txt)

Как повторить:
1. У меня получилось лишь раз вызвать краш, покрошив рандомный осколок из Forbidden Magic на воина с помощью серебродревесной мельницы. У меня не получилось воспроизвести ошибку, но надеюсь, что репорт поможет.

**Comment by Ilya3point999K** [comment]
Краш происходит из-за механики ускорения параноиков когда они получают урон, что именно крашит - непонятно, пока вырежу эту механику, верну когда придумаю фикс или альтернативу.

**Comment by Danilux112** [comment]
Привет =)
Первый раз пишу на Гитхабе, не уверен, что файлы прикрепятся корректно, заранее прошу прощения, если вдруг не прикрепятся=)
Писал ранее на Minecraft-inside, но там не сумел в личные сообщения, поэтому пишу тут.
не получается запустить майн с модом, помирает на пост-инициализации, прилагаю краш репорт:
[crash-2024-07-11_15.36.09-client.txt](https://github.com/user-attachments/files/16180705/crash-2024-07-11_15.36.09-client.txt)


Как будто бы он не может запустить какой-то Field, который получается из набалдашников для террастали, и консоль это выдаёт даже в отсутствие Ботании как таковой. Происходит это в сочетании с любым из двух других аддонов Таума: Tainted Magic и Thaumic Bases (с Ботанией в целом и террасталью в частности не связанных вообще никак, что очень странно), с остальными всё работает, наконец пойду изучать сам мод =) 

Надеюсь, получится разобраться, в чём казус, успехов =)

![image](https://github.com/Ilya3point999K/ThaumicConcilium/assets/175336308/07b2a1ce-01aa-4308-bca8-cd8ed1982d8a)

**Comment by Ilya3point999K** [comment]
Ты используешь сильно устаревшие версии модов, работоспособность Консилиума гарантируется только с последними версиями всех перечисленных в совместимостях модов. Помимо Forbidden Magic проверь версии всех остальных аддонов - Tainted Magic, Thaumic Bases, ну и остальные
![image](https://github.com/user-attachments/assets/5b4e6813-2b3f-42dc-84d7-2b1e90d8689e)
