### ISSUE TITLE
Crash when trying to view the KAMI-ingredient researches when it's turned off

### ISSUE THREAD

**Issue by RaidhoSketch** [Ilya3point999K/ThaumicConcilium#21]
Like, we know that it's rare that one turns it off, but, like, we only installed the ttinkerer to test how the mod works
(it's really a shame that it's an obligate dependency, considering how almost all the others are optional)

**Comment by Ilya3point999K** [comment]
Unfortunately, disabling of KAMI is not supported. Kinda silly that you install addon about expansion of other addons, and then cut half of their content ;)
