### ISSUE TITLE
Issues with the Paranoid Warrior.

### ISSUE THREAD

**Issue by xxXCuriositykilledthecatXxx** [Ilya3point999K/ThaumicConcilium#22]
The Paranoid Warrior can hit you through walls when he switches to his wand. 
[Wall hacks.webm](https://github.com/user-attachments/assets/9b8a948e-9d6f-4071-8852-d03659ba7c51)
He drops broken items depending on the variant.
![afsdgavvvvsgw3rwrty](https://github.com/user-attachments/assets/a144e01c-6a67-48f9-a9d3-49c091cb294b)
It also seems a variant of the Paranoid Warrior wearing armor from Tainted Magic causes the game to crash when killed.
https://mclo.gs/FGmDAMg

**Comment by Ilya3point999K** [comment]
My bad, 1.0.6 patch is upcoming today.
