### ISSUE TITLE
Game crash caused by envy dust with continuous arrows

### ISSUE THREAD

**Issue by FantasyShark** [Ilya3point999K/ThaumicConcilium#23]
I used dispenser with redstone cycle to test the envy dust. And when it shot arrows continuously the envy dust just duplicated itself more and more then caused the game crashing.

**Comment by FantasyShark** [comment]
By the way which lang file is the original one? I am translating the mod to Chinese and found some difference between en_US and ru_RU.

**Comment by FantasyShark** [comment]
> By the way which lang file is the original one? I am translating the mod to Chinese and found some difference between en_US and ru_RU.

**Comment by Ilya3point999K** [comment]
Eh, problem with crahes resolved?
Originally I've translated from ru_RU to en_US, but there shouldn't be any crucial differencies, pick whatever you want.

**Comment by FantasyShark** [comment]
Nope. The closing is a mistaken touch. :)

**Comment by Ilya3point999K** [comment]
How much you've build up envy dust? If it's hundreds of hundreds, I guess there are very little I can do. It duplicated because you continued to supply arrows, or is it duplicated on its own?

**Comment by FantasyShark** [comment]
It seems that every envy dust will transform every arrow nearby at the same time. So if you continue to shoot arrows in a high rate  the game will crash eventually because of too much entities. It might be avoidable but is still a potential danger.

**Comment by Ilya3point999K** [comment]
So you mean there are multiple envy dusts from one arrow? I'll check that.
