### ISSUE TITLE
Проблема спавна тауматургов

### ISSUE THREAD

**Issue by ProstoIEgor** [Ilya3point999K/ThaumicConcilium#26]
Писал на "minecraft inside", но там коммент не публикуют долго, а на Curse Forge я очень сухо описал проблему. 
В общем, у меня в мирах вообще не спавнятся тауматурги. Бегаю по 2 часа по миру и ни одного, при том, что остальные мобы из аддона спавнятся без проблем. В конфигах все по стандарту стоит (10), хотя уже выставлял разные значения - результата нет. Мод переустанавливал, бегал искал их до того как изучил их в таумономиконе и после - безрезультатно. 
Спавнил в мире в креативке: ничего не крашится, торгуют нормально. Однако вот что заметил: при наведении на них таумометром они отображаются как "entity.thaumicconcilium.thaumaturge.name" вместо обычного их имени. С другими мобами опять-таки такой проблемы нет. 
Мир новый создавал - все еще ничего.
В чем может быть проблема?

_P.s. правда, что ты за год написал аддон, включая то, что изучал моддинг?_

**Comment by Ilya3point999K** [comment]
Может у тебя стоят моды на изменение генерации мира, которые меняют ванильные биомы? Скинь список модов в сборке.
То, что у них имя кривое, это мой косяк, он будет исправлен в следующем патче, проблема мелкая, поэтому я жду пока ошибок побольше накопится.
Ну да, примерно год +- полгода.

**Comment by ProstoIEgor** [comment]
![изображение_2024-08-27_123219859](https://github.com/user-attachments/assets/da1a27de-94e2-4b82-b97a-e36a46a88ee2)
![изображение_2024-08-27_123243521](https://github.com/user-attachments/assets/ea3d0ed5-d109-4400-b33e-e10451c9dca4)
![изображение_2024-08-27_123258513](https://github.com/user-attachments/assets/cab4d26d-35bd-44ff-965a-fed9cdf688e4)

**Comment by ProstoIEgor** [comment]
По предварительным тестам проблема состоит в моде "thaumcraft mob aspect". Я убрал его, создал мир с айди 999 (просто по рандому) и вокруг меня заспавнилось сразу много (штук 6 поодаль друг от друга), летая по миру не нашел ни одного. А потом создал другой и ни одного ни сразу, ни в следствие поисков

**Comment by Ilya3point999K** [comment]
Может моды ни на что не влияли, просто не везло?

**Comment by ProstoIEgor** [comment]
Ну, смотри. Вот я сейчас снес вообще все под чистую, создаю миры и тестирую. Выявил, что иногда они спавнятся в большом количестве при запуске мира, а потом до свидания. Причем они стоят либо в кучках, либо с животными, будто они при генерации заменили какого-то моба (может так и есть). 
Я тоже думал о невезении, но вот если так прикинуть, насколько часто они должны мне попадаться в мире?
Смотря на враждебных мобов ночью, я как раз и ожидал примерного такого же количества наших собратьев.

P.s.  Я понимаю, тебя возможно чуток подзадолбало, просто мне прям очень нравится твой аддон и вот охота все его моменты прочувствовать :D

**Comment by Ilya3point999K** [comment]
Нет, тауматурги никого не заменяют, они появляются днем как и все мирные мобы. В майнкрафте обычно все овцы с коровами активно спавнятся при генерации мира, а потом как-то тухленько, мне кажется, что если они в принципе физически спавнятся - то все норм, а остальное просто рандом.

**Comment by ProstoIEgor** [comment]
Теперь бы разобраться, как кристалл в инфузию запихать...Очень интересно, но очень сложно

**Comment by ProstoIEgor** [comment]
а как интегрировать эссенцию внутрь _гекса предсказуемости?_

**Comment by Ilya3point999K** [comment]
Об этом написано в изучении астрального монитора, подай редстоун сигнал вис-конденсатору снизу

**Comment by ProstoIEgor** [comment]
![изображение_2024-09-03_135853693](https://github.com/user-attachments/assets/454c6a6f-6778-4448-9522-21a138c6dae3)
не понимаю, вот конденсаторы, везде снизу по включенному рычагу. Все изучено. Начинаю процесс по порядку (Cognitio) - взрыв. Чудом несколько раз получилось без взрыва начать. В итоге вроде все забрал, но как таумометр кинуть - не понимаю.
И даже не понятно насчет сигнала редстоуна - включен вис конденсатор или нет, анимация может быть нужна🤔

**Comment by Ilya3point999K** [comment]
Вот видео инструкция - https://youtu.be/pWEI2avY0Dc?si=3ZAuSuLJeW68qyG_
Рекомендую задавать вопросы на сервере в дискорде, там я отвечаю быстрее, чем тут
![image](https://github.com/user-attachments/assets/c5300666-f705-4aa2-967c-647e60e3bccf)

**Comment by ProstoIEgor** [comment]
хорошо, спасибо)

**Comment by ProstoIEgor** [comment]
![image](https://github.com/user-attachments/assets/cea2c3b3-54a8-4306-9a89-0a0f5110bf16)
