### ISSUE TITLE
Crash ThaumicConcilium-1.0.8

### ISSUE THREAD

**Issue by PROJonYz** [Ilya3point999K/ThaumicConcilium#29]
Проверил на работаспособность данный мод, хотел добавить его в свой модпак, но мод крашится если добавить ThaumicBases 2.1.0 и TaintedMagic 1.1.6.4 хоть на CurseForge написано что мод должен поддерживать ThaumicBases и TaintedMagic, не так-ли?

Краш репорт: https://pastebin.com/Q2fBfFw8

**Comment by Ilya3point999K** [comment]
Обнови Forbidden Magic
![image](https://github.com/user-attachments/assets/d6a3ec6d-97e5-4dc2-bcb9-efe833165e7c)
![image](https://github.com/user-attachments/assets/71a28358-ffd5-444c-899a-776d24d14f0a)

**Comment by PROJonYz** [comment]
Спс, обновка модов помогло, эт чет я тупанул пока сонным пытался разобратся)
