### ISSUE TITLE
Визуальные дефекты на Молоте Понтифика

### ISSUE THREAD

**Issue by GedeonGrays** [Ilya3point999K/ThaumicConcilium#3]
Привет о/

1. Съехала текстура
![2024-07-05_16 05 36](https://github.com/Ilya3point999K/ThaumicConcilium/assets/32182901/873cdd65-e7c0-45fa-9d62-b098984e1fc9)
![2024-07-05_16 05 47](https://github.com/Ilya3point999K/ThaumicConcilium/assets/32182901/18b6ec79-c027-4578-90ae-bf265651187a)

2. Щели в модельке (возможно, есть ещё)
![2024-07-05_16 20 09](https://github.com/Ilya3point999K/ThaumicConcilium/assets/32182901/e6c47838-28e8-4752-9280-d2c5e36aa339)
![2024-07-05_16 22 36](https://github.com/Ilya3point999K/ThaumicConcilium/assets/32182901/cd4ab931-ca7f-4233-b34f-d6fb0d22a065)

**Comment by Ilya3point999K** [comment]
Перекинуто художнику, ожидаем

**Comment by Ilya3point999K** [comment]
Исправлено в последнем коммите
