### ISSUE TITLE
Alternative method to kill the dissolved

### ISSUE THREAD

**Issue by xxXCuriositykilledthecatXxx** [Ilya3point999K/ThaumicConcilium#33]
The dissolved being functionally immortal outside of the portable hole focus causes a lot of frustration for players not focusing on thaumcraft. Considering how this mod leans into the multiplayer aspect with a number of it's items, I think it would be fitting to give the dissolved an alternate method of death similar to the Quicksilver elemental. I purpose making it so a ender pearl can kill/remove the enemy when used on it. This would still make the dissolved a significant threat while also preventing others on a server from being severely punished for not focusing thaumcraft. I'd also suggest for this alternate method to not give void seeds.

**Comment by Ilya3point999K** [comment]
Death by enderpearls makes sense, however dissolved can be killed without portable hole focus - he can be lured into his own hole, which will make him suffocate in blocks.
