### ISSUE TITLE
Ethereal Manipulator works oddly near a rift

### ISSUE THREAD

**Issue by FantasyShark** [Ilya3point999K/ThaumicConcilium#34]
The item kept falling when I dragged it near to the rift. It happened every time no matter the rift was chained or not and bothered me a lot during the void permeation.

**Comment by Ilya3point999K** [comment]
Ethereal manipulator scan for entity can sometimes stuck in large rift hitbox. Also mechanic of uplifting item for permeation seems to be sensible to lags on server, I will change it in next patch, when I'll have spare time.
Could you also provide me your e-mail (you can send it to my e-mail on my github page, if you don't want publicity), so I can send you .lang changes for keeping chinese translation up to date before release? Of course, if you are want to.

**Comment by FantasyShark** [comment]
Of course, I'm glad to. And does this mean there will be more new content?

**Comment by Ilya3point999K** [comment]
There certainly will be bugfixes, and there may be new content when I'll get to it

**Comment by FantasyShark** [comment]
> There certainly will be bugfixes, and there may be new content when I'll get to it

Fantastic.
