### ISSUE TITLE
Несколько визуальных странностей

### ISSUE THREAD

**Issue by GedeonGrays** [Ilya3point999K/ThaumicConcilium#4]
Привет о/

1. Щели в Астральном Мониторе
![2024-07-05_16 41 41](https://github.com/Ilya3point999K/ThaumicConcilium/assets/32182901/adf88a17-de71-4270-a36a-d569dca2e57c)

2. Непонятные элементы в левой части экрана при ударе Великодревесной/Серебродревесной Мельницей в режиме загрузки осколков
![2024-07-05_16 41 57](https://github.com/Ilya3point999K/ThaumicConcilium/assets/32182901/1a9360f3-4eb6-48d8-a0f7-f57448fc4ed5)
![2024-07-05_16 42 00](https://github.com/Ilya3point999K/ThaumicConcilium/assets/32182901/863f23bc-d20d-402c-956a-9fbdd72cb95e)

3. Не хватает части подошвы у модели Самосвальных Ботфортов
![2024-07-05_16 41 23](https://github.com/Ilya3point999K/ThaumicConcilium/assets/32182901/ee672153-f0ce-4f01-a519-fa56ffab2fe9)
![2024-07-05_16 41 30](https://github.com/Ilya3point999K/ThaumicConcilium/assets/32182901/95fc5943-adb5-452c-8320-d093aa85b9a2)

4. У Самоцвета Разломов/Terra-слепка что-то с внутренней частью модели
![2024-07-05_16 46 54](https://github.com/Ilya3point999K/ThaumicConcilium/assets/32182901/c4482c8d-21a3-422c-bcd5-b6318440ca68)
![2024-07-05_16 47 03](https://github.com/Ilya3point999K/ThaumicConcilium/assets/32182901/3a8f9081-1465-4506-b1e0-7e0aba3efb75)
![2024-07-05_16 46 45](https://github.com/Ilya3point999K/ThaumicConcilium/assets/32182901/59a16749-4d61-4d40-a404-99a93d92f24b)
![2024-07-05_16 46 50](https://github.com/Ilya3point999K/ThaumicConcilium/assets/32182901/03a1392d-dc9e-4642-81b0-aaeb02a55992)

**Comment by Ilya3point999K** [comment]
Монитор, мельница, ботфорты исправлены.
Отключение куллинга самоцветам сделало только хуже, оставлю как есть, никто не заметит
