### ISSUE TITLE
Краш с Taumic Bases и DummyCore

### ISSUE THREAD

**Issue by Frey426** [Ilya3point999K/ThaumicConcilium#8]
Когда подрубаю Taumic Bases и DummyCore игра крашится в конце загрузки, логи пишут, что ошибка в Консилиуме. Могу ошибаться, потому что плохо разбираюсь в этой теме

Логи:
https://paste.ee/p/gUmBi

**Comment by Ilya3point999K** [comment]
https://github.com/Ilya3point999K/ThaumicConcilium/issues/2#issuecomment-2224195008
Ты используешь сильно устаревшие версии модов, работоспособность Консилиума гарантируется только с последними версиями всех перечисленных в совместимостях модов. Помимо Forbidden Magic проверь версии всех остальных аддонов - Tainted Magic, Thaumic Bases, ну и так далее
![image](https://github.com/user-attachments/assets/890894cd-e694-434b-b95f-2194cd6ba339)
